apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-i8qm
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-i8qm
    app.kubernetes.io/part-of: tkrw-pr712-0075-0074-app
  name: devfile-sample-i8qm
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-i8qm
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-i8qm
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0074-tenant/tkrw-pr712-0075-0074-app/devfile-sample-i8qm@sha256:d01109fd06313696abfc0316203bfcd09b08318d99e9050a5cfaa97cbf93d9e9
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
